# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 02:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FLOW_RECEIVED', models.FloatField()),
                ('IN_BOD', models.FloatField()),
                ('IN_COD', models.FloatField()),
                ('IN_pH', models.FloatField()),
                ('IN_TSS', models.FloatField()),
                ('IN_TO', models.FloatField()),
                ('EF_BOD', models.FloatField()),
                ('EF_COD', models.FloatField()),
                ('EF_pH', models.FloatField()),
                ('EF_TSS', models.FloatField()),
                ('EF_DO', models.FloatField()),
                ('COMMENTS', models.TextField()),
                ('PUBLISHED_DATE', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
