# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='STP_NAME',
            field=models.CharField(choices=[('SNOWDON', 'Snowdon'), ('NORTH_DISPOSAL', 'North Disposal'), ('SUMMER_HILL', 'Summer Hill'), ('DHALLI', 'Dhalli'), ('SANJAULI_MALYANA', 'Sanjauli Malyana'), ('LALPANI', 'Lalpani')], default='SNOWDON', max_length=50),
        ),
    ]
