# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-21 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20160921_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='COMMENTS',
            field=models.TextField(blank=True, null=True),
        ),
    ]
