# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20160921_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='FLOW_RECEIVED',
            field=models.CharField(max_length=200),
        ),
    ]
