# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20160924_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='EF_BOD',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='EF_COD',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='EF_DO',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='EF_TSS',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='EF_pH',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='IN_BOD',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='IN_COD',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='IN_DO',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='IN_TSS',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='IN_pH',
            field=models.CharField(max_length=200),
        ),
    ]
